name: Project Handling CD STAGING

on:
    push:
        branches: [ "staging" ]

    pull_request:
        branches: [ "staging" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
                service_id: ${{ secrets.MY_RENDER_SERVICE_ID_STAGING }}
                api_key: ${{ secrets.MY_RENDER_API_KEY }}
                wait_deploy: true 